name: WLED compile

on:
    workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.9

    - name: Install PlatformIO
      run: |
        python -m pip install --upgrade pip
        pip install --upgrade platformio
    - name: Set up Node.js
      uses: actions/setup-node@v4
    - name: Run PlatformIO
      run: |
        rm -rf /tmp/WLEDtemp/* || true
        mkdir -p /tmp/WLEDtemp
        wget https://github.com/atuline/WLED/archive/refs/heads/dev.zip -O /tmp/WLEDtemp/mm.zip
        unzip /tmp/WLEDtemp/mm.zip -d /tmp/WLEDtemp
        find /tmp/WLEDtemp -maxdepth 1 -mindepth 1 -name "*" -type d >> /tmp/WLEDtemp/wledfoldername
        cd `cat /tmp/WLEDtemp/wledfoldername`
        npm install
        echo '[env:custom_build]' >>platformio.ini
        echo 'extends = env:esp32_16MB_M' >>platformio.ini
        echo 'build_flags = ${env:esp32_16MB_M.build_flags} -D SR_DEBUG -D MIC_LOGGER -D LOLIN_WIFI_FIX -D WLED_DEBUG -D WLED_DEBUG_IMPROV -D LEDPIN=0 -D WLED_MAX_BUTTONS=4 -D WLED_MAX_BUSSES=6 -D DEFAULT_LED_COUNT=561 -D ABL_MILLIAMPS_DEFAULT=4500 -D DEFAULT_LED_TYPE=TYPE_WS2812_RGB -D DEFAULT_LED_COLOR_ORDER=COL_ORDER_GRB -D WLED_MAX_LEDMAPS=156 -D MAX_LED_MEMORY=64000 -D CLIENT_SSID='\''"searching..."'\'' -D CLIENT_PASS='\''"onceuponapassword"'\'' -D USERMOD_SENSORSTOMQTT -D RGB_ROTARY_ENCODER -D USERMOD_ADS1115' >>platformio.ini
        echo 'lib_deps = ' >>platformio.ini
        echo '  ${env:esp32_16MB_M.lib_deps}' >>platformio.ini
        echo '  adafruit/Adafruit BMP280 Library @ 2.1.0' >>platformio.ini
        echo '  adafruit/Adafruit CCS811 Library @ 1.0.4' >>platformio.ini
        echo '  adafruit/Adafruit Si7021 Library @ 1.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor' >>platformio.ini
        echo '  lennarthennigs/ESP Rotary@^1.5.0' >>platformio.ini
        echo '  adafruit/Adafruit BusIO @ 1.13.2' >>platformio.ini
        echo '  adafruit/Adafruit ADS1X15 @ 2.4.0' >>platformio.ini
        echo '  adafruit/Adafruit Unified Sensor' >>platformio.ini
        
        pio run -e custom_build || pio run -e custom_build
    - name: Copy Files
      run: |
        cd $GITHUB_WORKSPACE
        git rm -r $GITHUB_WORKSPACE/*.bin || true
        WLEDFOLDERNAME=`cat /tmp/WLEDtemp/wledfoldername`
        cp ${WLEDFOLDERNAME}/build_output/firmware/custom_build.bin $GITHUB_WORKSPACE/
        date -I | tr -d '\n' >$GITHUB_WORKSPACE/last_update_date.txt
    - name: Commit Files
      run: |
        cd $GITHUB_WORKSPACE
        git config user.name "GitHub Actions Bot"
        git config user.email "<>"
        git add $GITHUB_WORKSPACE/custom_build.bin
        git add $GITHUB_WORKSPACE/last_update_date.txt
        git commit -m "Commit Custom Build"
        git push origin main
